In [1]:
import torch

In [2]:
torch.cuda.device_count()

1

In [7]:
fattyacid_serum_csv = "/global/D1/homes/vajira/data/sperm/visem/visem-dataset/fatty_acids_serum.csv"
fattyacid_spermatoza_csv = "/global/D1/homes/vajira/data/sperm/visem/visem-dataset/fatty_acids_spermatoza.csv"
participant_related_csv = "/global/D1/homes/vajira/data/sperm/visem/visem-dataset/participant_related_data.csv"
semen_analysis_data = "/global/D1/homes/vajira/data/sperm/visem/visem-dataset/semen_analysis_data.csv"
sex_hormones_csv = "/global/D1/homes/vajira/data/sperm/visem/visem-dataset/sex_hormones.csv"

In [10]:
# Read all csv files into dataframes
import pandas as pd

fattyacid_serum_df = pd.read_csv(fattyacid_serum_csv, delimiter=';')
fattyacid_spermatoza_df = pd.read_csv(fattyacid_spermatoza_csv, delimiter=';')
participant_related_df = pd.read_csv(participant_related_csv, delimiter=';')
semen_analysis_data_df = pd.read_csv(semen_analysis_data, delimiter=';')
sex_hormones_df = pd.read_csv(sex_hormones_csv, delimiter=';')

In [11]:
fattyacid_serum_df

,ID,Serum C14:0 (myristic acid),Serum C16:0 (palmitic acid),Serum C16:1 (palmitoleic acid),Serum C18:0 (stearic acid),Serum C18:1 n-9 (oleic acid),Serum total C18:1,"Serum C18:2 n-6 (linoleic acid, LA)","Serum C18:3 n-6 (gamma-linoleic acid, GLA)",Serum C20:1 n-9,Serum C20:2 n-6,Serum C20:3 n-6,Serum C20:4 n-6,"Serum C20:5 n-3 (eicosapentaenoic acid, EPA)","Serum C22:5 n-3 (docosapentaenoic acid, DPA)","Serum C22:6 n-3 (docosahexaenoic acid, DHA)"
0,1,"0,36","29,72","0,64","13,67","9,00","10,90","19,48","0,30","0,16","0,31","3,37","12,07","2,15","1,35","5,53"
1,2,"0,28","31,22","0,47","11,84","9,02","11,29","20,34","0,22","0,25","0,26","2,06","11,64","2,80","1,04","6,31"
2,3,"0,36","27,95","0,47","16,57","8,65","10,36","23,75","0,26","0,19","0,35","3,10","7,37","1,95","0,98","6,34"
3,4,"0,32","28,10","0,64","16,09","8,56","10,13","21,52","0,17","0,11","0,31","4,41","12,09","1,56","1,32","3,23"
4,5,"0,40","29,94","0,80","14,17","9,47","11,02","22,29","0,38","0,15","0,29","4,33","8,61","1,73","1,58","4,31"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,81,"0,26","29,96","0,40","12,38","10,03","11,81","23,36","0,17","0,18","0,24","2,46","8,48","1,85","1,38","7,08"
81,82,"0,24","26,62","0,26","15,03","8,24","10,62","27,21","0,23","0,31","0,38","2,42","8,19","1,32","1,27","5,92"
82,83,"0,39","29,48","0,68","12,12","12,97","15,13","23,03","0,26","0,22","0,19","2,68","10,25","1,05","1,37","3,14"
83,84,"0,22","26,68","0,30","14,74","7,57","9,82","24,73","0,22","0,19","0,27","1,47","10,11","2,16","1,34","7,74"
84,85,"0,22","27,00","0,33","15,26","9,93","11,89","22,88","0,11","0,34","0,30","3,95","11,05","1,58","0,31","4,79"

In [12]:
fattyacid_spermatoza_df.head()

,ID,Sperm C14:0 (myristic acid),Sperm C15:0 (pentadecanoic acid),Sperm C16:0 (palmitic acid),Sperm C16:1 n-7 (palmitoleic acid),Sperm C17:0,Sperm C18:0 (stearic acid),Sperm C18:1 trans n-6 to n-11,Sperm C18:1 n-9 (oleic acid),Sperm C18:1 n-7 to n-11,...,Sperm C20:1 n-9,Sperm C20:2 n-6,Sperm C22:0,Sperm C20:3 n-6,Sperm C20:4 n-6 and C22:1 n-9 combined,"Sperm C20:5 n-3 (eicosapentaenoic acid, EPA)",Sperm C24:0,Sperm C24:1 n-9,"Sperm C22:5 n-3 (docosapentaenoic acid, DPA)","Sperm C22:6,n3 (docosahexaenoic acid, DHA)"
0,1,"1,3","0,2","24,3","0,9","0,3","9,7","0,8","9,8","2,4",...,"0,4","0,5","0,1","4,2","2,5","0,06","1,0","1,2","1,3","25,3"
1,2,"1,5","0,2","26,3","1,3","0,3","8,9","0,9","12,1","2,7",...,"0,3","0,9","2,1","2,6","2,6","0,14","1,4","1,6","1,6","17,3"
2,3,"1,1","0,2","24,8","0,9","0,2","9,0","0,5","12,3","2,3",...,"0,4","0,4","1,9","2,2","3,2","0,17","1,7","2,0","1,1","21,5"
3,4,"1,1","0,2","22,8","1,0","0,3","9,4","0,9","18,2","2,4",...,"0,5","0,5","2,1","2,4","2,9","0,09","1,8","2,2","2,0","14,8"
4,5,"1,1","0,1","22,1","0,9","0,2","9,7","0,4","10,0","2,5",...,"0,4","0,7","0,6","4,9","3,0","0,05","1,0","1,5","1,0","26,6"

In [13]:
participant_related_df.head()

   ID Abstinence time(days) Body mass index (kg/m²)  Age (years)
0   1                   4,0                    32,5           36
1   2                   4,0                    33,7           61
2   3                   2,0                    62,7           51
3   4                   2,5                    45,5           38
4   5                   3,0                    51,0           33

In [16]:
semen_analysis_data_df.head()

,ID,Sperm concentration (x10⁶/mL),Total sperm count (x10⁶),Ejaculate volume (mL),Sperm vitality (%),Normal spermatozoa (%),Head defects (%),Midpiece and neck defects (%),Tail defects (%),Cytoplasmic droplet (%),Teratozoospermia index,Progressive motility (%),Non progressive sperm motility (%),Immotile sperm (%),"High DNA stainability, HDS (%)","DNA fragmentation index, DFI (%)"
0,1,"105,3","363,1","3,5",81,"2,0","98,0","11,2","38,0","3,4","1,54",51,19,30,13,29
1,2,"45,4","141,6","3,1",50,"3,0","97,0","8,5","24,5","2,0","1,36",22,16,62,13,57
2,3,"50,0","124,5","2,5",90,"6,9","90,6","32,8","14,3","1,5","1,51",18,26,56,11,12
3,4,"42,9","103,8","2,4",80,"2,8","96,5","24,1","23,1","5,2","1,53",33,26,41,10,15
4,5,"32,8","158,7","4,8",90,"3,2","95,0","32,5","15,7","7,0","1,56",43,22,35,21,13

In [17]:
sex_hormones_df.head()

,ID,Seminal plasma anti-Müllerian hormone (AMH) (pmol/L),Serum total testosterone (nmol/L),Serum oestradiol (nmol/L),"Serum sex hormone-binding globulin, SHBG (nmol/L)","Serum follicle-stimulating hormone, FSH (IU/L)","Serum Luteinizing hormone, LH (IU/L)",Serum inhibin B (ng/L),"Serum anti-Müllerian hormone, AMH (pmol/L)"
0,1,64,"16,8","0,13",15,"2,3","4,2",289,54
1,2,423,15,"0,15",43,"7,2","2,7",164,19
2,3,37,"8,2","0,18",32,"4,2","4,8",67,47
3,4,257,"11,2","0,15",11,"8,5","5,6",132,29
4,5,2203,"11,9","0,14",18,"2,6","2,1",139,68

In [18]:
# combine all dataframes into one using ID as the key
df = pd.merge(fattyacid_serum_df, fattyacid_spermatoza_df, on='ID')
df = pd.merge(df, participant_related_df, on='ID')
df = pd.merge(df, semen_analysis_data_df, on='ID')
df = pd.merge(df, sex_hormones_df, on='ID')

In [19]:
df.head()

,ID,Serum C14:0 (myristic acid),Serum C16:0 (palmitic acid),Serum C16:1 (palmitoleic acid),Serum C18:0 (stearic acid),Serum C18:1 n-9 (oleic acid),Serum total C18:1,"Serum C18:2 n-6 (linoleic acid, LA)","Serum C18:3 n-6 (gamma-linoleic acid, GLA)",Serum C20:1 n-9,...,"High DNA stainability, HDS (%)","DNA fragmentation index, DFI (%)",Seminal plasma anti-Müllerian hormone (AMH) (pmol/L),Serum total testosterone (nmol/L),Serum oestradiol (nmol/L),"Serum sex hormone-binding globulin, SHBG (nmol/L)","Serum follicle-stimulating hormone, FSH (IU/L)","Serum Luteinizing hormone, LH (IU/L)",Serum inhibin B (ng/L),"Serum anti-Müllerian hormone, AMH (pmol/L)"
0,1,"0,36","29,72","0,64","13,67","9,00","10,90","19,48","0,30","0,16",...,13,29,64,"16,8","0,13",15,"2,3","4,2",289,54
1,2,"0,28","31,22","0,47","11,84","9,02","11,29","20,34","0,22","0,25",...,13,57,423,15,"0,15",43,"7,2","2,7",164,19
2,3,"0,36","27,95","0,47","16,57","8,65","10,36","23,75","0,26","0,19",...,11,12,37,"8,2","0,18",32,"4,2","4,8",67,47
3,4,"0,32","28,10","0,64","16,09","8,56","10,13","21,52","0,17","0,11",...,10,15,257,"11,2","0,15",11,"8,5","5,6",132,29
4,5,"0,40","29,94","0,80","14,17","9,47","11,02","22,29","0,38","0,15",...,21,13,2203,"11,9","0,14",18,"2,6","2,1",139,68

In [20]:
# change the ID column name to file_name
df.rename(columns={'ID': 'file_name'}, inplace=True)

In [21]:
df

,file_name,Serum C14:0 (myristic acid),Serum C16:0 (palmitic acid),Serum C16:1 (palmitoleic acid),Serum C18:0 (stearic acid),Serum C18:1 n-9 (oleic acid),Serum total C18:1,"Serum C18:2 n-6 (linoleic acid, LA)","Serum C18:3 n-6 (gamma-linoleic acid, GLA)",Serum C20:1 n-9,...,"High DNA stainability, HDS (%)","DNA fragmentation index, DFI (%)",Seminal plasma anti-Müllerian hormone (AMH) (pmol/L),Serum total testosterone (nmol/L),Serum oestradiol (nmol/L),"Serum sex hormone-binding globulin, SHBG (nmol/L)","Serum follicle-stimulating hormone, FSH (IU/L)","Serum Luteinizing hormone, LH (IU/L)",Serum inhibin B (ng/L),"Serum anti-Müllerian hormone, AMH (pmol/L)"
0,1,"0,36","29,72","0,64","13,67","9,00","10,90","19,48","0,30","0,16",...,13,29,64,"16,8","0,13",15,"2,3","4,2",289,54
1,2,"0,28","31,22","0,47","11,84","9,02","11,29","20,34","0,22","0,25",...,13,57,423,15,"0,15",43,"7,2","2,7",164,19
2,3,"0,36","27,95","0,47","16,57","8,65","10,36","23,75","0,26","0,19",...,11,12,37,"8,2","0,18",32,"4,2","4,8",67,47
3,4,"0,32","28,10","0,64","16,09","8,56","10,13","21,52","0,17","0,11",...,10,15,257,"11,2","0,15",11,"8,5","5,6",132,29
4,5,"0,40","29,94","0,80","14,17","9,47","11,02","22,29","0,38","0,15",...,21,13,2203,"11,9","0,14",18,"2,6","2,1",139,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,81,"0,26","29,96","0,40","12,38","10,03","11,81","23,36","0,17","0,18",...,8,14,15,"24,4","0,12",43,"4,7","3,7",206,48
81,82,"0,24","26,62","0,26","15,03","8,24","10,62","27,21","0,23","0,31",...,13,8,7,"28,9","0,14",52,"6,9","3,5",172,32
82,83,"0,39","29,48","0,68","12,12","12,97","15,13","23,03","0,26","0,22",...,8,16,79,"21,2","0,11",31,"1,7",4,263,70
83,84,"0,22","26,68","0,30","14,74","7,57","9,82","24,73","0,22","0,19",...,5,15,31,"34,5","0,13",63,"2,3","3,7",200,37
84,85,"0,22","27,00","0,33","15,26","9,93","11,89","22,88","0,11","0,34",...,4,24,4105,"14,1","0,1",49,"5,8","6,9",205,21

In [23]:
# add .avi to the file_name
df['file_name'] = df['file_name'].astype(str) + '.avi'

In [24]:
df

,file_name,Serum C14:0 (myristic acid),Serum C16:0 (palmitic acid),Serum C16:1 (palmitoleic acid),Serum C18:0 (stearic acid),Serum C18:1 n-9 (oleic acid),Serum total C18:1,"Serum C18:2 n-6 (linoleic acid, LA)","Serum C18:3 n-6 (gamma-linoleic acid, GLA)",Serum C20:1 n-9,...,"High DNA stainability, HDS (%)","DNA fragmentation index, DFI (%)",Seminal plasma anti-Müllerian hormone (AMH) (pmol/L),Serum total testosterone (nmol/L),Serum oestradiol (nmol/L),"Serum sex hormone-binding globulin, SHBG (nmol/L)","Serum follicle-stimulating hormone, FSH (IU/L)","Serum Luteinizing hormone, LH (IU/L)",Serum inhibin B (ng/L),"Serum anti-Müllerian hormone, AMH (pmol/L)"
0,1.avi,"0,36","29,72","0,64","13,67","9,00","10,90","19,48","0,30","0,16",...,13,29,64,"16,8","0,13",15,"2,3","4,2",289,54
1,2.avi,"0,28","31,22","0,47","11,84","9,02","11,29","20,34","0,22","0,25",...,13,57,423,15,"0,15",43,"7,2","2,7",164,19
2,3.avi,"0,36","27,95","0,47","16,57","8,65","10,36","23,75","0,26","0,19",...,11,12,37,"8,2","0,18",32,"4,2","4,8",67,47
3,4.avi,"0,32","28,10","0,64","16,09","8,56","10,13","21,52","0,17","0,11",...,10,15,257,"11,2","0,15",11,"8,5","5,6",132,29
4,5.avi,"0,40","29,94","0,80","14,17","9,47","11,02","22,29","0,38","0,15",...,21,13,2203,"11,9","0,14",18,"2,6","2,1",139,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,81.avi,"0,26","29,96","0,40","12,38","10,03","11,81","23,36","0,17","0,18",...,8,14,15,"24,4","0,12",43,"4,7","3,7",206,48
81,82.avi,"0,24","26,62","0,26","15,03","8,24","10,62","27,21","0,23","0,31",...,13,8,7,"28,9","0,14",52,"6,9","3,5",172,32
82,83.avi,"0,39","29,48","0,68","12,12","12,97","15,13","23,03","0,26","0,22",...,8,16,79,"21,2","0,11",31,"1,7",4,263,70
83,84.avi,"0,22","26,68","0,30","14,74","7,57","9,82","24,73","0,22","0,19",...,5,15,31,"34,5","0,13",63,"2,3","3,7",200,37
84,85.avi,"0,22","27,00","0,33","15,26","9,93","11,89","22,88","0,11","0,34",...,4,24,4105,"14,1","0,1",49,"5,8","6,9",205,21

In [25]:
# save the dataframe to a csv file named metadata.csv in the directory "/global/D1/homes/vajira/data/sperm/visem/visem-dataset"
df.to_csv('/global/D1/homes/vajira/data/sperm/visem/visem-dataset/metadata.csv', index=False)